# name of your docker build pipeline
name: Java CI 05 for build and push docker image to docker hub
run-name: ${{ github.actor }} creates new docker image

# will run on every push
on: [ push ]

jobs:
  deliver:
    runs-on: ubuntu-latest

    # define single steps which has to be run
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          # will cache .m2 directory and will be loaded if pom.xml will be changed
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      # https://github.com/docker/build-push-action
      # https://docs.docker.com/build/ci/github-actions/

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # will push to public repository
      - name: Build and push to public repository
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/democalc_public:latest

      # will push to private repository
      - name: Build and push to private repository
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/demo_private:latest