# name of our first pipeline
name: Java CI 01 for compile sources
run-name: ${{ github.actor }} runs compile sources 🚀

# will run on every push
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    # define single steps which has to be run
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
