# name of our first pipeline
name: Java CI 03 for compile sources (with cache)
run-name: ${{ github.actor }} runs compile sources (with cache) 🚀

# will run on every push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    # define single steps which has to be run
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          # will cache .m2 directory and will be loaded if pom.xml will be changed
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package